name: Build and Test app
on: [pull_request, push]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_PROJECT: ${{ 'SampleIOSApp.xcodeproj' }}
      XC_SCHEME: ${{ 'SampleIOSApp' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'i
